(
BOT_INFO_KEY,
BEGINNING_QUIZ_KEY,
SECOND_QUESTION_KEY,
THIRD_QUESTION_KEY,
FOURTH_QUESTION_KEY,
FIFTH_QUESTION_KEY,
POLICY_KEY,
MAIN_MENU_KEY
) = map(chr, range(8))

(
BACK_KEY,
ADD_USER_TRAIN_KEY,
GENERATE_TRAIN_KEY,
CHOICE_TRAIN_KEY,
) = map(chr, range(8, 12))

(
GO_2_PUSH_UP_TEST_KEY,
PUSH_UP_TEST_KEY,
RUNNING_3KM_TEST_KEY,
SQUAT_TEST_KEY,
PRESS_TEST_KEY,
PULL_UP_TEST_KEY
) = map(chr, range(12, 18))


(
    TYPE_TRAIN_KEY,
    GENERATE_TRAIN_KEY,
    FAST_TRAIN_KEY,
    STANDART_TRAIN_KEY,
    STRATCHING_KEY,
    CHOICE_FOOD_KEY,
    GEN_EX_KEY,
    END_GENERATION_TRAIN_KEY
) = map(chr, range(18, 26))

(
    SET_USER_DATA_KEY,
    CHOICE_SETTINGS_KEY,
    SET_GENDER_KEY,
    SET_AGE_KEY,
    SET_HEIGHT_KEY,
    SET_WEIGHT_KEY,
    SET_GOAL_KEY,
    CHOICE_PROGRESS_KEY
) = map(chr, range(26, 34))