from .bot_info_keyboard import reply_markup_about_bot_keyboard
from .goal_choice_keyboard import goal_choice_keyboard
from .gender_choice_keyboard import gender_choice_keyboard
from .policy_agree_keyboard import policy_agree_keyboard
from .main_menu_keyboard import main_menu_keyboard
from .settings_keyboard import settings_keyboard
from .user_settings_keyboard import user_settings_keyboard
from .progress_keyboard import progress_keyboard