"""'initial'

Revision ID: 8a563b80228f
Revises: 
Create Date: 2023-05-14 16:32:01.529774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a563b80228f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_advices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('complexity_levels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('compl_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compl_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('dishes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kilocalories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('is_piece', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('default_weight', sa.Integer(), nullable=False),
    sa.Column('max_weight', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('feelings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('feeling_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feeling_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('genders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gender_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gender_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('goal_name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('inv_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('inv_name')
    )
    op.create_table('muscules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('muscule_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('muscule_name')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('review_name')
    )
    op.create_table('type_workouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('types_workout_exercise',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('advices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories_advices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('text')
    )
    op.create_table('exercises',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ex_name', sa.String(length=255), nullable=False),
    sa.Column('complexity_level_id', sa.BigInteger(), nullable=False),
    sa.Column('type_exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('inventories_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technices', sa.Text(), nullable=False),
    sa.Column('image_exercise_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['complexity_level_id'], ['complexity_levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventories_id'], ['inventories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_exercise_id'], ['types_workout_exercise.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ex_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_agree', sa.Boolean(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('calendar_statistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type_workout_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('feeling_id', sa.Integer(), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feeling_id'], ['feelings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_workout_id'], ['type_workouts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_workouts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('values', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'exercise_id')
    )
    op.create_table('muscule_exercise_groups',
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('muscules_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscules_id'], ['muscules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'muscules_id')
    )
    op.create_table('muscule_users_groups',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('muscules_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['muscules_id'], ['muscules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'muscules_id')
    )
    op.create_table('user_workouts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('exercise_user_workouts',
    sa.Column('train_id', sa.BigInteger(), nullable=False),
    sa.Column('exercise_id', sa.BigInteger(), nullable=False),
    sa.Column('approach_count', sa.Integer(), nullable=True),
    sa.Column('values', sa.String(length=255), nullable=True),
    sa.Column('relax_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['user_workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('train_id', 'exercise_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_user_workouts')
    op.drop_table('user_workouts')
    op.drop_table('muscule_users_groups')
    op.drop_table('muscule_exercise_groups')
    op.drop_table('exam_workouts')
    op.drop_table('calendar_statistics')
    op.drop_table('users')
    op.drop_table('exercises')
    op.drop_table('advices')
    op.drop_table('types_workout_exercise')
    op.drop_table('type_workouts')
    op.drop_table('reviews')
    op.drop_table('muscules')
    op.drop_table('inventories')
    op.drop_table('goals')
    op.drop_table('genders')
    op.drop_table('feelings')
    op.drop_table('dishes')
    op.drop_table('complexity_levels')
    op.drop_table('categories_advices')